default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  username: root
  password: root 
  host: 127.0.0.1
  port: 3306
  database: randa_development

test:
  <<: *default
  username: root
  password: root 
  host: 127.0.0.1
  port: 3306
  database: randa_testing
